@main
enum PhysicalInputStateTests {
    static func main() {
        var state = PhysicalInputState()
        state.seed(keys: [55], buttons: [0])
        precondition(state.keys == [55] && state.buttons == [0])
        state.key(55, down: false, posted: false)
        state.button(0, down: false, posted: false)
        // Regression: posting a down changes the OS snapshot, but must not
        // make ActionEngine or Smart output suppress the matching key-up.
        state.key(126, down: true, posted: true)
        state.button(0, down: true, posted: true)
        precondition(state.keys.isEmpty && state.buttons.isEmpty)
        state.seed(keys: [126], buttons: [0])
        precondition(state.keys.isEmpty && state.buttons.isEmpty)
        // A real press during an injected hold still owns the release.
        state.key(126, down: true, posted: false)
        state.button(0, down: true, posted: false)
        state.seed(keys: [126], buttons: [0])
        precondition(state.keys == [126] && state.buttons == [0])
        state.key(126, down: false, posted: true)
        state.button(0, down: false, posted: true)
        precondition(state.keys == [126] && state.buttons == [0])
        state.key(126, down: false, posted: false)
        state.button(0, down: false, posted: false)
        precondition(state.keys.isEmpty && state.buttons.isEmpty)
        // Idle snapshots seed real holds; left/right modifiers are distinct.
        state.seed(keys: [54, 55], buttons: [1])
        state.key(55, down: false, posted: false)
        precondition(state.keys == [54] && state.buttons == [1])
        state.seed(keys: [], buttons: [])
        precondition(state.keys.isEmpty && state.buttons.isEmpty)
        state.modifier(58, flags: 0x080020)
        precondition(state.keys == [58], "Option press comes from the event, not a lagging HID snapshot")
        state.modifier(61, flags: 0x080060)
        state.modifier(58, flags: 0x080040)
        precondition(state.keys == [61], "Releasing left Option preserves right Option")
        state.modifier(61, flags: 0)
        precondition(state.keys.isEmpty)
        state.modifier(56, flags: 0x020002)
        precondition(state.keys == [56])
        state.modifier(56, flags: 0)
        precondition(state.keys.isEmpty)
        state.modifier(55, flags: 0x100000)
        precondition(state.keys == [55], "Virtual modifier events can omit side masks")
        state.modifier(55, flags: 0)
        precondition(state.keys.isEmpty)
        print("PhysicalInputState tests passed")
    }
}
